# Project Information
site_name: Nima's Documentation
site_url: https://neurogranberg.github.io/Nima_Documentation/
site_description: Central Documentation of my project as RA in NG group, KI.
site_author: "Nima Chamyani"
repo_url: https://github.com/NeuroGranberg/Nima_Documentation
repo_name: Nima_Documentation
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2024 - Department of Clinical Neuroscience Neuroradiology, Karolinska Institutet, Sweden

theme:
  name: material
  language: en
  logo: assets/NG_GROUP.png
  favicon: assets/NG-T.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  features:
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - navigation.footer
    - content.action.edit
    - content.tooltips
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - announce.dismiss
    - content.action.view
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.share
    - toc.follow

# Navigation Structure
nav:
  - What is this: index.md
  - Settings:
    - settings/credential.md
  - iAID: 
    - iAID/chek_up.md
  # - Blog:
  #     - blog/index.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/NeuroGranberg/Nima_Documentation
      name: Nima_Documentation

plugins:
  - blog:
      enabled: true
      blog_dir: blog
      authors: true
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.arithmatex:
      generic: true
  - toc:
      toc_depth: 3

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
  
# Build Settings
use_directory_urls: true
